services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432" # host:container (keeps it separate from the other project on 5432)
    environment:
      POSTGRES_USER: tgtg
      POSTGRES_PASSWORD: tgtg-password
      POSTGRES_DB: tgtg_db
    volumes:
      - tgtg_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tgtg -d tgtg_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
      PORT: 3000

      # IMPORTANT: db (service name), not localhost
      DATABASE_URL: postgres://tgtg:tgtg-password@db:5432/tgtg_db
      DB_SSL: "false"

      JWT_SECRET: a7ec9a328c2eb75d39f8c2f2cf5b3c24440a82f19b7d0db25562fb60d7debec636e0dc79d5963ea072a4c7c18e37ad56
      JWT_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 30d

      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      COOKIE_DOMAIN: ""

      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
      SESSION_FINGERPRINT_SECRET: dev_fingerprint_secret_very_secure_very_long_very_secret_very_nice_very_mysterious
      SESSION_FINGERPRINT_STRICT: "false"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migration:run:prod && node dist/main.js"

volumes:
  tgtg_db_data:
